[package]
name = "rename_but_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

regex = "1.9.1"
walkdir = "2.3.3"
egui = "0.22.0"
eframe = "0.22.0"
serde_json = "1.0.100"
