[package]
name = "rename_but_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

regex = "1.7.0"
walkdir = "2.3.2"
egui = "0.20.0"
eframe = "0.20.1"